# Generated by Django 6.0.5 on 2026-05-08 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('incidents', '0002_ticket_sla_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อโปรเจกต์')),
                ('status', models.CharField(choices=[('Planning', 'วางแผน (Planning)'), ('Active', 'กำลังดำเนินการ (Active)'), ('On Hold', 'รอดำเนินการ (On Hold)'), ('Completed', 'เสร็จสิ้น (Completed)')], default='Planning', max_length=20, verbose_name='สถานะ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้องาน')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดส่ง')),
                ('priority', models.CharField(choices=[('Low', 'ต่ำ (Low)'), ('Medium', 'ปานกลาง (Medium)'), ('High', 'สูง (High)'), ('Critical', 'วิกฤต (Critical)')], default='Medium', max_length=10, verbose_name='ความสำคัญ')),
                ('status', models.CharField(choices=[('Todo', 'รอทำ (Todo)'), ('Doing', 'กำลังทำ (Doing)'), ('Done', 'เสร็จแล้ว (Done)')], default='Todo', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='โปรเจกต์')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='incidents.ticket', verbose_name='Ticket ที่เกี่ยวข้อง')),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
            },
        ),
    ]
