# Generated by Django 6.0.5 on 2026-05-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อลูกค้า')),
                ('note', models.TextField(blank=True, null=True, verbose_name='บันทึกเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='customers.customer')),
            ],
        ),
    ]
