# Generated by Django 6.0.5 on 2026-05-08 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='สังกัด/แผนก')),
                ('phone', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='วันที่ขอเข้าใช้งาน')),
                ('note', models.TextField(blank=True, null=True, verbose_name='บันทึกเพิ่มเติม')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
