# Generated by Django 6.0.5 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_executive_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('email', 'Email'), ('ip', 'IP address')], max_length=5)),
                ('key_hash', models.CharField(max_length=64)),
                ('window_started_at', models.DateTimeField()),
                ('request_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('key_type', 'key_hash'),
                        name='accounts_password_reset_rate_limit_key',
                    ),
                ],
            },
        ),
    ]
