# Generated by Django 6.0.5 on 2026-07-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordchangeaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SOC_STAFF', 'SOC Staff'), ('SOC_MANAGER', 'SOC Manager'), ('SYSTEM_ADMIN', 'System Admin'), ('SYSTEM_OWNER', 'System Owner'), ('EXECUTIVE', 'Executive'), ('FORENSIC', 'Forensic Analyst'), ('REDTEAM_MANAGER', 'Red Team Manager')], max_length=20, verbose_name='บทบาท'),
        ),
    ]
