# Generated by Django 6.0.7 on 2026-09-03 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountlockoutaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True)),
                ('throttling_failure_count', models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this device was initially created in the system.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='The most recent date and time this device was used.', null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('encrypted_secret', models.TextField(editable=False)),
                ('setup_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_t', models.BigIntegerField(default=-1)),
                ('recovery_codes_confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFAAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('event', models.CharField(choices=[('enrolled', 'Authenticator enrolled'), ('verified', 'Authenticator verified'), ('failed', 'Verification failed'), ('recovery_used', 'Recovery code used'), ('codes_generated', 'Recovery codes generated'), ('reset', 'Authenticator reset')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(editable=False, max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='accounts.authenticatordevice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='authenticatordevice',
            constraint=models.UniqueConstraint(fields=('user',), name='one_authenticator_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mfarecoverycode',
            constraint=models.UniqueConstraint(fields=('device', 'digest'), name='unique_mfa_recovery_code'),
        ),
    ]
