# Generated by Django 6.0.7 on 2026-09-03 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_authenticatordevice_mfaaudit_mfarecoverycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatordevice',
            name='recovery_generation',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
