# Generated by Django 6.0.7 on 2026-09-15 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_authenticatordevice_recovery_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acting_tier_access',
            field=models.BooleanField(default=False, verbose_name='สิทธิ์ทำงานระดับ Tier ชั่วคราว'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acting_tier_granted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ให้สิทธิ์เมื่อ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acting_tier_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_tier_grants', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ให้สิทธิ์'),
        ),
    ]
