# Generated by Django 6.0.7 on 2026-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_acting_tier_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfaaudit',
            name='event',
            field=models.CharField(choices=[('enrolled', 'ลงทะเบียนแอปยืนยันตัวตนแล้ว'), ('verified', 'ยืนยันตัวตนสำเร็จ'), ('failed', 'ยืนยันตัวตนไม่สำเร็จ'), ('recovery_used', 'ใช้รหัสกู้คืนแล้ว'), ('codes_generated', 'สร้างรหัสกู้คืนแล้ว'), ('reset', 'รีเซ็ตแอปยืนยันตัวตนแล้ว')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SOC_STAFF', 'เจ้าหน้าที่ SOC'), ('SOC_MANAGER', 'ผู้จัดการ SOC'), ('SYSTEM_ADMIN', 'ผู้ดูแลระบบ'), ('SYSTEM_OWNER', 'เจ้าของระบบ'), ('EXECUTIVE', 'ผู้บริหาร'), ('FORENSIC', 'นักวิเคราะห์นิติวิทยาศาสตร์ดิจิทัล'), ('REDTEAM_MANAGER', 'ผู้จัดการ Red Team')], max_length=20, verbose_name='บทบาท'),
        ),
    ]
