# Generated by Django 6.0.7 on 2026-09-25 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_mfaaudit_event_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='redteam_function',
            field=models.CharField(blank=True, choices=[('VA', 'Vulnerability Assessment (VA)'), ('PENTEST', 'Penetration Test'), ('HARDENING', 'Hardening')], default='', help_text='กำหนดให้บัญชีผู้จัดการ Red Team หนึ่งคนต่อหนึ่งประเภทงาน', max_length=20, verbose_name='งาน Red Team ที่รับผิดชอบ'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'REDTEAM_MANAGER'), models.Q(('redteam_function', ''), _negated=True)), fields=('redteam_function',), name='unique_redteam_manager_per_function'),
        ),
    ]
