# Generated by Django 6.0.5 on 2026-07-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggDetectionDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('rule_level', models.PositiveSmallIntegerField()),
                ('alert_count', models.BigIntegerField()),
                ('agent_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detection daily aggregate',
                'verbose_name_plural': 'Detection daily aggregates',
                'db_table': 'mart"."agg_detection_daily',
                'constraints': [models.UniqueConstraint(fields=('day', 'rule_level'), name='uq_detection_grain')],
            },
        ),
        migrations.CreateModel(
            name='SnapshotQueueDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=10)),
                ('age_bucket', models.CharField(max_length=10)),
                ('ola_bucket', models.CharField(max_length=12)),
                ('open_count', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Queue snapshot (daily)',
                'verbose_name_plural': 'Queue snapshots (daily)',
                'db_table': 'mart"."snapshot_queue_daily',
                'indexes': [models.Index(fields=['snapshot_date'], name='ix_snapshot_date')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'status', 'severity', 'age_bucket', 'ola_bucket'), name='uq_snapshot_grain')],
            },
        ),
    ]
