# Generated by Django 6.0.7 on 2026-10-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_ticket_cancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotKpiDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('open_tickets', models.PositiveIntegerField()),
                ('unassigned_open', models.PositiveIntegerField()),
                ('emergency_open_tickets', models.PositiveIntegerField()),
                ('emergency_open_incidents', models.PositiveIntegerField()),
                ('oldest_open_hours', models.PositiveIntegerField(null=True)),
                ('response_open', models.PositiveIntegerField()),
                ('response_aged_7d', models.PositiveIntegerField()),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'KPI snapshot (daily)',
                'verbose_name_plural': 'KPI snapshots (daily)',
                'db_table': 'mart"."snapshot_kpi_daily',
            },
        ),
        migrations.CreateModel(
            name='HistAlertDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('severity_band', models.CharField(max_length=10)),
                ('ingested_count', models.BigIntegerField()),
                ('triaged_count', models.BigIntegerField()),
                ('true_positive_count', models.BigIntegerField()),
                ('false_positive_count', models.BigIntegerField()),
                ('escalated_count', models.BigIntegerField()),
                ('became_ticket_count', models.BigIntegerField()),
                ('triage_ola_applicable', models.BigIntegerField()),
                ('triage_ola_met', models.BigIntegerField()),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Alert funnel history (daily)',
                'verbose_name_plural': 'Alert funnel history (daily)',
                'db_table': 'mart"."hist_alert_daily',
                'constraints': [models.UniqueConstraint(fields=('day', 'severity_band'), name='uq_hist_alert_grain')],
            },
        ),
        migrations.CreateModel(
            name='SnapshotResponseDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('subtask_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('aged_7d', models.BooleanField()),
                ('hc_ticket', models.BooleanField()),
                ('open_count', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Response-request snapshot (daily)',
                'verbose_name_plural': 'Response-request snapshots (daily)',
                'db_table': 'mart"."snapshot_response_daily',
                'indexes': [models.Index(fields=['snapshot_date'], name='ix_response_snapshot_date')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'subtask_type', 'status', 'aged_7d', 'hc_ticket'), name='uq_response_snapshot_grain')],
            },
        ),
        migrations.CreateModel(
            name='SnapshotWorkloadDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('kind', models.CharField(max_length=12)),
                ('user_id', models.IntegerField(null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=10)),
                ('open_count', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Workload snapshot (daily)',
                'verbose_name_plural': 'Workload snapshots (daily)',
                'db_table': 'mart"."snapshot_workload_daily',
                'indexes': [models.Index(fields=['snapshot_date'], name='ix_workload_date')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'kind', 'user_id', 'status', 'severity'), name='uq_workload_grain')],
            },
        ),
    ]
