# Generated by Django 6.0.5 on 2026-06-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WazuhAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opensearch_id', models.CharField(db_index=True, help_text='OpenSearch document _id — used for deduplication.', max_length=64, unique=True)),
                ('alert_id', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('agent_id', models.CharField(blank=True, default='', max_length=16)),
                ('agent_name', models.CharField(blank=True, default='', max_length=128)),
                ('agent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('rule_id', models.CharField(blank=True, default='', max_length=32)),
                ('rule_level', models.PositiveSmallIntegerField()),
                ('rule_description', models.TextField(blank=True, default='')),
                ('rule_groups', models.JSONField(blank=True, default=list)),
                ('mitre_techniques', models.JSONField(blank=True, default=list)),
                ('mitre_tactics', models.JSONField(blank=True, default=list)),
                ('mitre_ids', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('decoder_name', models.CharField(blank=True, default='', max_length=64)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
