# Generated by Django 6.0.5 on 2026-06-11 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazuh_ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wazuhalert',
            name='escalated_to_tier',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('MANAGER', 'Manager')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wazuhalert',
            name='triage_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wazuhalert',
            name='triage_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='wazuhalert',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wazuhalert',
            name='triaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
