# Generated by Django 6.0.5 on 2026-06-11 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazuh_ingest', '0002_wazuhalert_escalated_to_tier_wazuhalert_triage_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wazuhalert',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wazuhalert',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wazuhalert',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('Malware', 'Malware'), ('Phishing', 'Phishing'), ('Unauthorized Access', 'Unauthorized Access'), ('Data Exfiltration', 'Data Exfiltration'), ('Denial of Service', 'Denial of Service'), ('Reconnaissance', 'Reconnaissance'), ('Policy Violation', 'Policy Violation'), ('Other', 'Other')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='wazuhalert',
            name='triage_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRIAGING', 'Triaging'), ('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=16),
        ),
    ]
