# Generated by Django 6.0.5 on 2026-06-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazuh_ingest', '0003_wazuhalert_claimed_at_wazuhalert_claimed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wazuhalert',
            name='release_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
