# Generated by Django 6.0.7 on 2026-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazuh_ingest', '0007_wazuhalert_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wazuhalert',
            name='escalated_to_tier',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('MANAGER', 'ผู้จัดการ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wazuhalert',
            name='kind',
            field=models.CharField(choices=[('DETECTION', 'การตรวจจับ'), ('VULNERABILITY', 'ช่องโหว่')], db_index=True, default='DETECTION', help_text='Whether this alert is triage work or vulnerability inventory.', max_length=16),
        ),
        migrations.AlterField(
            model_name='wazuhalert',
            name='triage_status',
            field=models.CharField(choices=[('PENDING', 'รอคัดกรอง'), ('TRIAGING', 'กำลังคัดกรอง'), ('TRUE_POSITIVE', 'Incident'), ('FALSE_POSITIVE', 'Event'), ('ESCALATED', 'ส่งต่อแล้ว')], default='PENDING', max_length=16),
        ),
    ]
