# Generated by Django 6.0.5 on 2026-05-08 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('device_name', models.CharField(max_length=100, verbose_name='IP Source')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Destination')),
                ('issue_description', models.TextField(verbose_name='รายละเอียด')),
                ('status', models.CharField(choices=[('Open', 'รอดำเนินการ'), ('In Progress', 'กำลังแก้ไข'), ('Resolved', 'แก้ไขแล้ว'), ('Closed', 'ปิดงาน')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('update_notes', models.TextField(blank=True, null=True, verbose_name='บันทึกการติดตามงาน')),
                ('category', models.CharField(choices=[('Cyber Event', 'Cyber Event'), ('Incident', 'Incident'), ('Cyber Event/Incident', 'Cyber Event/Incident')], default='Cyber Event', max_length=50, verbose_name='Category')),
                ('issue_type', models.CharField(choices=[('SIEM', 'ระบบเฝ้าระวัง (SIEM)'), ('Admin', 'ผู้ดูแลระบบ (Admin)'), ('TI', 'Threat Intelligence (TI)'), ('External', 'หน่วยงานภายนอก (External organization)')], default='SIEM', max_length=50, verbose_name='Type')),
                ('detailed_issue', models.CharField(choices=[('Training', 'เหตุการณ์จำลอง และ การฝึกจู่โจม ของหน่วยงานเอง (Training and Exercises)'), ('Unsuccessful Attempt', 'การพยายามเข้าถึงระบบที่ไม่สำเร็จ (Unsuccessful Activity Attempt)'), ('Reconnaissance', 'การพยายามบุกรุกเพื่อสำรวจข้อมูลองค์กรเพื่อโจมตี (Reconnaissance)'), ('Non-Compliance', 'การดำเนินการที่ไม่เป็นไปตามมาตรฐานความปลอดภัยที่หน่วยงานกำหนด (Non-Compliance Activity)'), ('Malicious Logic', 'การบุกรุกโดยการใช้มัลแวร์ (Malicious Logic)'), ('User Intrusion', 'การบุกรุกในระดับผู้ใช้งาน (User Level Intrusion)'), ('Root Intrusion', 'การบุกรุกในระดับผู้ควบคุมระบบ (Root Level Intrusion)'), ('DoS', 'การบุกรุกที่ทำให้ไม่สามารถเข้าไปใช้บริการได้ (Denial of Service)'), ('Investigating', 'เหตุการณ์ที่อยู่ระหว่างการวิเคราะห์สอบสวน (Investigating)'), ('Explained Anomaly', 'เหตุการณ์ผิดปกติที่ได้รับการวิเคราะห์แล้วว่าไม่ใช่เหตุการณ์ที่เป็นภัยคุกคาม (Explained Anomaly)'), ('SIEM Other', 'อื่นๆ (SIEM Other)'), ('Admin Unsuccessful', '(Admin) การพยายามเข้าถึงระบบที่ไม่สำเร็จ (Unsuccessful Activity Attempt)'), ('Admin Reconnaissance', '(Admin) การพยายามบุกรุกเพื่อสำรวจข้อมูลองค์กรเพื่อโจมตี (Reconnaissance)'), ('Admin Non-Compliance', '(Admin) การดำเนินการที่ไม่เป็นไปตามมาตรฐานความปลอดภัยที่หน่วยงานกำหนด (Non-Compliance Activity)'), ('Admin Malicious Logic', '(Admin) การบุกรุกโดยการใช้มัลแวร์ (Malicious Logic)'), ('Admin User Intrusion', '(Admin) การบุกรุกในระดับผู้ใช้งาน (User Level Intrusion)'), ('Admin Root Intrusion', '(Admin) การบุกรุกในระดับผู้ควบคุมระบบ (Root Level Intrusion)'), ('Admin DoS', '(Admin) การบุกรุกที่ทำให้ไม่สามารถเข้าไปใช้บริการได้ (Denial of Service)'), ('Admin Explained Anomaly', '(Admin) เหตุการณ์ผิดปกติที่ได้รับการวิเคราะห์แล้วว่าไม่ใช่เหตุการณ์ที่เป็นภัยคุกคาม (Explained Anomaly)'), ('TI IOC', 'แจ้งเตือน IOC (Indicators of Compromise)'), ('TI Other', 'อื่นๆ (TI Other)'), ('Data Leak', 'พบข้อมูลรั่วไหล'), ('Vulnerability', 'พบช่องโหว่ของอุปกรณ์หรือระบบงาน'), ('Attack Attempt', 'พบความพยายามในการไปโจมตีผู้อื่น'), ('External Other', 'อื่นๆ (External Other)')], default='Investigating', max_length=255, verbose_name='เหตุการณ์ที่พบ (Detailed Issue)')),
                ('detailed_issue2', models.CharField(choices=[('Admin Failed Login', '(Admin) Login ล้มเหลวหลายครั้ง (failed login) จากบัญชีเดียวกัน'), ('Admin Panel Block', '(Admin) การพยายามเข้าถึง URL/admin panel และได้ 403/401'), ('Data Leak Detail', '(External) พบข้อมูลรั่วไหล'), ('Attack Attempt Detail', '(External) พบความพยายามในการไปโจมตีผู้อื่น'), ('Vulnerability Found', '(External) พบช่องโหว่ของอุปกรณ์หรือระบบงาน'), ('External Other Detail', '(External) อื่นๆ (External Other)'), ('TI Malicious IP', '(TI) พบการติดต่อกับ IP อันตราย (Malicious IP Communication)'), ('TI IOC Detail', '(TI) แจ้งเตือน IOC (Indicators of Compromise)'), ('Data Exfiltration', 'Access ไฟล์สำคัญจำนวนมากในเวลาสั้น (data exfiltration)'), ('Admin Maintenance', 'Admin ทำงาน maintenance นอกเวลาปกติ'), ('Server Spike', 'CPU / Memory server พุ่งสูงผิดปกติ'), ('DNS Enumeration', 'DNS enumeration (query domain ย่อยจำนวนมาก)'), ('Spam Account', 'Email account ถูกใช้ส่ง spam/phishing'), ('SOC Escalate', 'Event ถูก escalate ไป SOC analyst'), ('Firewall Block', 'Firewall block การเชื่อมต่อจาก IP ที่ต้องสงสัย'), ('Whitelisted Log', 'Log แสดง activity จาก IP ภายในที่ถูก whitelist เป็น "test range"'), ('Failed Login', 'Login ล้มเหลวหลายครั้ง (failed login) จากบัญชีเดียวกัน'), ('Impossible Travel', 'Login สำเร็จจาก location แปลก (Impossible travel)'), ('DoS Other', 'Other (Denial of Service)'), ('Explained Other', 'Other (Explained Anomaly)'), ('Investigating Other', 'Other (Investigating)'), ('Malicious Other', 'Other (Malicious Logic)'), ('Compliance Other', 'Other (Non-Compliance Activity)'), ('Recon Other', 'Other (Reconnaissance)'), ('Root Level Other', 'Other (Root Level Intrusion)'), ('Training Other', 'Other (Training and Exercises)'), ('Unsuccessful Other', 'Other (Unsuccessful Activity Attempt)'), ('User Level Other', 'Other (User Level Intrusion)'), ('Port Scanning', 'Port scanning จาก IP ภายนอก (เช่น scan port 22, 80, 443)'), ('Suspicious PowerShell', 'PowerShell execution ที่ suspicious (encoded command)'), ('Brute Force', 'Red Team ทำการ brute force test กับระบบ'), ('Unconfirmed Login', 'SIEM alert ว่า "suspicious login" แต่ยังไม่ confirm'), ('SSH Failed', 'SSH login failed หลายครั้ง (brute force attempt)'), ('SYN Flood', 'SYN flood attack'), ('Vulnerability Scanner', 'Scan มาจาก vulnerability scanner ภายใน'), ('Deploy Traffic', 'Traffic สูงเพราะมีการ deploy ระบบ / backup'), ('HTTP Flood', 'Traffic เข้ามาจำนวนมากผิดปกติ (HTTP flood)'), ('User Enumeration', 'User enumeration เช่น ลอง login ด้วย username หลายๆ แบบ'), ('VPN Login', 'User login จากต่างประเทศ แต่จริงๆ คือ VPN ของบริษัท'), ('USB Policy', 'User ใช้ USB storage ทั้งที่ policy ห้าม'), ('Web Scanning', 'Web scanning เช่น /admin, /backup, /test'), ('Admin Panel Attempt', 'การพยายามเข้าถึง URL/admin panel และได้ 403/401'), ('Internal Scan', 'การสแกนช่องโหว่จากเครื่องมือภายใน เช่น Nexus / OpenVAS'), ('Log Gathering', 'กำลังรวบรวม log จากหลายแหล่ง (Firewall, endpoint, AD)'), ('Malware EDR', 'ตรวจพบ malware จาก EDR (เช่น Trojan, ransomware)'), ('Unauthorized Software', 'ติดตั้ง software ที่ไม่ได้รับอนุญาต'), ('Antivirus Off', 'ปิด antivirus / endpoint protection'), ('Log Service Off', 'ปิด log / security service'), ('Anomaly Correlation', 'พบ anomaly แต่ยังต้อง correlation เพิ่ม'), ('Simulated Phishing', 'พบการยิง simulated phishing campaign จากทีม security'), ('DDoS', 'มี request ซ้ำๆ จำนวนมากจากหลาย IP (DDoS)'), ('C2 Server', 'มีการเรียก command & control (C2) server'), ('Privilege Escalation', 'มีการใช้ sudo / privilege escalation สำเร็จ'), ('Abnormal Account', 'มีการใช้บัญชี user รับคำสั่งผิดปกติ'), ('Unauthorized Admin', 'สร้าง admin account ใหม่โดยไม่ได้รับอนุญาต'), ('SIEM Other Detail', 'อื่นๆ (SIEM Other)'), ('System Config Change', 'แก้ไข system binaries หรือ config สำคัญ'), ('Weak Password', 'ใช้ password ที่ไม่ตรง policy (เช่น ไม่มี complexity)'), ('Ransomware Behavior', 'ไฟล์ถูก encrypt จำนวนมาก (ransomware behavior)')], default='Investigating Other', max_length=255, verbose_name='เรื่องที่แจ้ง')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้เปิดงาน')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='บันทึกรายละเอียด')),
                ('status_at_time', models.CharField(max_length=20, verbose_name='สถานะขณะบันทึก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='ผู้บันทึก')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='incidents.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
