# Generated by Django 6.0.5 on 2026-05-25
#
# Changes Ticket.assigned_to and TicketLog.author from CharField to FK(User).
# Existing string values cannot be mapped to User PKs, so the old columns are
# dropped and replaced with nullable FK columns (all existing rows get NULL).
# This is intentional data loss — only affects the assignee/author strings,
# not any ticket content.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_ticket_sla_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ticket.assigned_to: drop CharField, add FK(User, null=True).
        # Existing string assignee values are lost (set to null).
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_tickets',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # TicketLog.author: drop CharField, add FK(User, null=True).
        # Existing string author values are lost (set to null).
        migrations.RemoveField(
            model_name='ticketlog',
            name='author',
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ticket_logs',
                to=settings.AUTH_USER_MODEL,
                verbose_name='ผู้บันทึก',
            ),
        ),
    ]
