# Generated by Django 6.0.5 on 2026-06-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_system_owner_fk_and_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('Computer', 'Computer'), ('Server', 'Server'), ('Network Device', 'Network Device')], default='', max_length=20, verbose_name='ประเภทของทรัพย์สิน'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination_ip',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='IP Address ปลายทางที่น่าสงสัย'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='incident_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันและเวลาที่ตรวจพบเหตุการณ์'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ioc_details',
            field=models.TextField(blank=True, default='', verbose_name='Indicators of Compromise (IoC)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='MAC Address'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mitre_phase',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Phase การโจมตีตาม MITRE ATT&CK'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reference_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remediation_summary',
            field=models.TextField(blank=True, default='', verbose_name='สรุปผลการดำเนินการแก้ไข'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=10, verbose_name='ระดับความรุนแรง'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='spread_to_others',
            field=models.BooleanField(blank=True, null=True, verbose_name='มีการกระจายไปยังจุดอื่น'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='device_name',
            field=models.CharField(max_length=100, verbose_name='ระบบ / บริการ (System/Service)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address ของทรัพย์สิน'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_description',
            field=models.TextField(verbose_name='รายละเอียดเหตุการณ์'),
        ),
    ]
