# Generated by Django 6.0.5 on 2026-06-11 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_report_fields'),
        ('wazuh_ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='wazuh_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='wazuh_ingest.wazuhalert', verbose_name='Wazuh Alert'),
        ),
    ]
