# Generated by Django 6.0.5 on 2026-06-11 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_ticket_wazuh_alert'),
        ('wazuh_ingest', '0003_wazuhalert_claimed_at_wazuhalert_claimed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='source',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone / Hotline'), ('USER_REPORT', 'User / Internal Report'), ('EXTERNAL', 'External Organization'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='แหล่งที่มาของ Alert'),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='source_reference',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='รหัสอ้างอิงจากแหล่งที่มา'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='wazuh_alert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='wazuh_ingest.wazuhalert', verbose_name='Wazuh Alert'),
        ),
    ]
