# Generated by Django 6.0.5 on 2026-06-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_triagerecord_source_triagerecord_source_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='action_precautions',
            field=models.TextField(blank=True, default='', verbose_name='ข้อควรระวังในการดำเนินการ'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='action_required',
            field=models.TextField(blank=True, default='', verbose_name='สิ่งที่ต้องดำเนินการ'),
        ),
    ]
