# Generated by Django 6.0.5 on 2026-06-12 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_ticket_action_precautions_ticket_action_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_type', models.CharField(choices=[('INVESTIGATION', 'Investigation'), ('COUNTERMEASURE', 'Countermeasure')], max_length=20, verbose_name='ประเภท')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อ')),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียด')),
                ('status', models.CharField(choices=[('OPEN', 'เปิด'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('DONE', 'เสร็จสิ้น')], default='OPEN', max_length=20, verbose_name='สถานะ')),
                ('result_notes', models.TextField(blank=True, default='', verbose_name='ผลการดำเนินการ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_subtasks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subtasks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='incidents.ticket', verbose_name='Ticket หลัก')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
