# Generated by Django 6.0.5 on 2026-06-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_ticketsubtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('CONTAINMENT_REQUIRED', 'แจ้งผู้ดูแลระบบ — ต้องดำเนินการควบคุม (Containment required)'), ('OWNER_CREATED', 'แจ้งเจ้าของระบบ — เปิด Ticket ใหม่'), ('OWNER_CLOSED', 'แจ้งเจ้าของระบบ — ปิด Ticket แล้ว')], max_length=50, unique=True, verbose_name='ประเภทการแจ้งเตือน')),
                ('subject', models.CharField(max_length=255, verbose_name='หัวข้ออีเมล')),
                ('body', models.TextField(verbose_name='เนื้อหาอีเมล')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
