# Generated by Django 6.0.5 on 2026-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_notificationtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='key',
            field=models.CharField(choices=[('CONTAINMENT_REQUIRED', 'แจ้งผู้ดูแลระบบ — ต้องดำเนินการควบคุม (Containment required)'), ('CONTAINMENT_SUBMITTED', 'แจ้งเจ้าหน้าที่ SOC — ผู้ดูแลระบบส่งรายงานการควบคุมแล้ว'), ('OWNER_CREATED', 'แจ้งเจ้าของระบบ — เปิด Ticket ใหม่'), ('OWNER_CLOSED', 'แจ้งเจ้าของระบบ — ปิด Ticket แล้ว')], max_length=50, unique=True, verbose_name='ประเภทการแจ้งเตือน'),
        ),
    ]
