# Generated by Django 6.0.5 on 2026-06-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_rename_disposition_to_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalated_to_t2_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ส่งต่อ Tier 2 ครั้งแรก'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='เหตุฉุกเฉิน (Emergency)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='classification',
            field=models.CharField(blank=True, choices=[('INCIDENT', 'Incident (เหตุการณ์จริง)'), ('EVENT', 'Event (ไม่เป็นภัย)')], default='', max_length=20, verbose_name='การจัดประเภท (Event/Incident)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'แจ้งเหตุใหม่'), ('ESCALATED_T2', 'ส่งต่อให้ Tier 2'), ('T1_REVIEW', 'รอ Tier 1 ทบทวน'), ('AWAITING_CONTAINMENT', 'รอการจัดการจากผู้ดูแลระบบ'), ('CONTAINMENT_REPORTED', 'รายงานการควบคุมแล้ว'), ('PENDING_MANAGER', 'รอผู้จัดการตรวจสอบ'), ('APPROVED', 'อนุมัติแล้ว'), ('CLOSED_EVENT', 'ปิด (Event)')], default='NEW', max_length=30),
        ),
    ]
