# Generated by Django 6.0.5 on 2026-06-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0019_manual_triage_intake_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='High', max_length=10, verbose_name='ระดับความรุนแรง'),
        ),
    ]
