# Generated by Django 6.0.5 on 2026-06-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_unknown_severity_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='alert_conversion_duration',
            field=models.DurationField(blank=True, help_text='created_at − wazuh_alert.ingested_at, stamped once at creation.', null=True, verbose_name='เวลาตอบสนอง (Alert พร้อมรับ → เปิด Ticket)'),
        ),
    ]
