# Generated by Django 6.0.5 on 2026-06-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0023_backfill_alert_conversion_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
    ]
