# Generated by Django 6.0.5 on 2026-06-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0024_remove_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('SIEM', 'ระบบเฝ้าระวัง (SIEM)'), ('ADMIN', 'ผู้ดูแลระบบ (Admin)'), ('TI', 'Threat Intelligence (TI)'), ('EMAIL', 'Email'), ('PHONE', 'Phone / Hotline'), ('USER_REPORT', 'User / Internal Report'), ('EXTERNAL', 'หน่วยงานภายนอก (External Organization)'), ('OTHER', 'Other')], default='SIEM', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='source',
            field=models.CharField(choices=[('SIEM', 'ระบบเฝ้าระวัง (SIEM)'), ('ADMIN', 'ผู้ดูแลระบบ (Admin)'), ('TI', 'Threat Intelligence (TI)'), ('EMAIL', 'Email'), ('PHONE', 'Phone / Hotline'), ('USER_REPORT', 'User / Internal Report'), ('EXTERNAL', 'หน่วยงานภายนอก (External Organization)'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='แหล่งที่มาของ Alert'),
        ),
    ]
