# Generated by Django 6.0.5 on 2026-07-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0028_rename_ticket_sla_deadline_ola_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ola_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OLA Deadline'),
        ),
    ]
