# Generated by Django 6.0.5 on 2026-07-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0030_split_ola_deadlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่รับเคส'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='alert_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='คะแนน Alert (TrendMicro)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ปิดเคส'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='report_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ออกรายงาน'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Address ของทรัพย์สิน'),
        ),
    ]
