# Generated by Django 6.0.5 on 2026-07-06 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0031_ticket_acknowledged_at_ticket_alert_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bundle_suffix',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='ลำดับในกลุ่ม (A, B, C …)'),
        ),
        migrations.CreateModel(
            name='ProjectIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='รหัส Project Incident')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อเหตุการณ์')),
                ('summary', models.TextField(blank=True, default='', verbose_name='รายละเอียดโดยรวม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_incidents', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เปิดเหตุการณ์')),
            ],
            options={
                'verbose_name': 'Project Incident (Case Bundle)',
                'verbose_name_plural': 'Project Incidents (Case Bundles)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='project_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_tickets', to='incidents.projectincident', verbose_name='Project Incident (Case Bundle)'),
        ),
    ]
