# Generated by Django 6.0.5 on 2026-07-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0032_ticket_bundle_suffix_projectincident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='project_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_triages', to='incidents.projectincident', verbose_name='Project Incident (Case Bundle)'),
        ),
    ]
