# Generated by Django 6.0.5 on 2026-07-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0033_triagerecord_project_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='incident_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ชื่อเหตุการณ์ (Incident/Event Name)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ncsa_severity',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'วิกฤต (Critical)'), ('SEVERE', 'ร้ายแรง (Severe)'), ('NON_SEVERE', 'ไม่ร้ายแรง (Non-Severe)')], default='', max_length=20, verbose_name='ระดับความรุนแรงตาม สกมช.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='operating_system',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ระบบปฏิบัติการ (Operating System)'),
        ),
    ]
