# Generated by Django 6.0.5 on 2026-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0034_ticket_incident_name_ticket_ncsa_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset_owner',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='หน่วยงานเจ้าของทรัพย์สิน'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='log_source',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='แหล่งข้อมูล (Log Source)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mitre_phase',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Phase การโจมตีตาม MITRE ATT&CK'),
        ),
    ]
