# Generated by Django 6.0.5 on 2026-07-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0036_ticket_direct_owner_remediation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'แจ้งเหตุใหม่'), ('ESCALATED_T2', 'ส่งต่อให้ Tier 2'), ('T1_REVIEW', 'รอ Tier 1 ทบทวน'), ('AWAITING_CONTAINMENT', 'รอการจัดการจากผู้ดูแลระบบ'), ('CONTAINMENT_REPORTED', 'รายงานการควบคุมแล้ว'), ('AWAITING_OWNER', 'รอเจ้าของระบบดำเนินการเอง'), ('OWNER_REMEDIATED', 'เจ้าของแจ้งแก้ไขแล้ว — รอ SOC ตรวจ'), ('PENDING_T2_REVIEW', 'รอ Tier 2 ตรวจสอบ'), ('PENDING_MANAGER', 'รอผู้จัดการตรวจสอบ'), ('APPROVED', 'อนุมัติแล้ว'), ('CLOSED_EVENT', 'ปิด (Event)')], default='NEW', max_length=30),
        ),
    ]
