# Generated by Django 6.0.5 on 2026-07-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0038_ticket_report_export_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='report_format',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
