# Generated by Django 6.0.5 on 2026-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0039_ticket_report_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_issue', models.CharField(choices=[('Training', 'เหตุการณ์จำลอง และ การฝึกจู่โจม ของหน่วยงานเอง (Training and Exercises)'), ('Unsuccessful Attempt', 'การพยายามเข้าถึงระบบที่ไม่สำเร็จ (Unsuccessful Activity Attempt)'), ('Reconnaissance', 'การพยายามบุกรุกเพื่อสำรวจข้อมูลองค์กรเพื่อโจมตี (Reconnaissance)'), ('Non-Compliance', 'การดำเนินการที่ไม่เป็นไปตามมาตรฐานความปลอดภัยที่หน่วยงานกำหนด (Non-Compliance Activity)'), ('Malicious Logic', 'การบุกรุกโดยการใช้มัลแวร์ (Malicious Logic)'), ('User Intrusion', 'การบุกรุกในระดับผู้ใช้งาน (User Level Intrusion)'), ('Root Intrusion', 'การบุกรุกในระดับผู้ควบคุมระบบ (Root Level Intrusion)'), ('DoS', 'การบุกรุกที่ทำให้ไม่สามารถเข้าไปใช้บริการได้ (Denial of Service)'), ('Investigating', 'เหตุการณ์ที่อยู่ระหว่างการวิเคราะห์สอบสวน (Investigating)'), ('Explained Anomaly', 'เหตุการณ์ผิดปกติที่ได้รับการวิเคราะห์แล้วว่าไม่ใช่เหตุการณ์ที่เป็นภัยคุกคาม (Explained Anomaly)'), ('SIEM Other', 'อื่นๆ (SIEM Other)'), ('Admin Unsuccessful', '(Admin) การพยายามเข้าถึงระบบที่ไม่สำเร็จ (Unsuccessful Activity Attempt)'), ('Admin Reconnaissance', '(Admin) การพยายามบุกรุกเพื่อสำรวจข้อมูลองค์กรเพื่อโจมตี (Reconnaissance)'), ('Admin Non-Compliance', '(Admin) การดำเนินการที่ไม่เป็นไปตามมาตรฐานความปลอดภัยที่หน่วยงานกำหนด (Non-Compliance Activity)'), ('Admin Malicious Logic', '(Admin) การบุกรุกโดยการใช้มัลแวร์ (Malicious Logic)'), ('Admin User Intrusion', '(Admin) การบุกรุกในระดับผู้ใช้งาน (User Level Intrusion)'), ('Admin Root Intrusion', '(Admin) การบุกรุกในระดับผู้ควบคุมระบบ (Root Level Intrusion)'), ('Admin DoS', '(Admin) การบุกรุกที่ทำให้ไม่สามารถเข้าไปใช้บริการได้ (Denial of Service)'), ('Admin Explained Anomaly', '(Admin) เหตุการณ์ผิดปกติที่ได้รับการวิเคราะห์แล้วว่าไม่ใช่เหตุการณ์ที่เป็นภัยคุกคาม (Explained Anomaly)'), ('TI IOC', 'แจ้งเตือน IOC (Indicators of Compromise)'), ('TI Other', 'อื่นๆ (TI Other)'), ('Data Leak', 'พบข้อมูลรั่วไหล'), ('Vulnerability', 'พบช่องโหว่ของอุปกรณ์หรือระบบงาน'), ('Attack Attempt', 'พบความพยายามในการไปโจมตีผู้อื่น'), ('External Other', 'อื่นๆ (External Other)')], max_length=50, unique=True, verbose_name='หมวดหมู่ภัยคุกคาม')),
                ('action_required', models.TextField(blank=True, default='', verbose_name='สิ่งที่ต้องดำเนินการ (มาตรฐาน)')),
                ('action_precautions', models.TextField(blank=True, default='', verbose_name='ข้อควรระวังในการดำเนินการ (มาตรฐาน)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'แนวทางมาตรฐานตามหมวดหมู่ภัยคุกคาม',
                'verbose_name_plural': 'แนวทางมาตรฐานตามหมวดหมู่ภัยคุกคาม',
                'ordering': ['detailed_issue'],
            },
        ),
    ]
