# Generated by Django 6.0.5 on 2026-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0041_seed_threat_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='containment_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
