# Generated by Codex on 2026-07-10

from django.db import migrations


def migrate_ticket_references(apps, schema_editor):
    Ticket = apps.get_model('incidents', 'Ticket')
    active_month = None
    sequence = 0

    # A Ticket Reference records when this system opened the ticket. Ordering
    # existing tickets by that creation timestamp gives each historical month a
    # deterministic, contiguous sequence.
    for ticket in Ticket.objects.order_by('created_at', 'pk').iterator():
        created_at = ticket.created_at
        month = (created_at.year, created_at.month)
        if month != active_month:
            active_month = month
            sequence = 0
        sequence += 1
        Ticket.objects.filter(pk=ticket.pk).update(
            ticket_id=f'SOC-{created_at.year:04d}{created_at.month:02d}-{sequence:04d}',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0042_ticket_containment_checklist'),
    ]

    operations = [
        migrations.RunPython(migrate_ticket_references, migrations.RunPython.noop),
    ]
