# Generated by Django 6.0.5 on 2026-07-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0043_migrate_ticket_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t1_route',
            field=models.CharField(blank=True, choices=[('ADMIN', 'มอบหมายผู้ดูแลระบบ (System Admin)'), ('OWNER', 'ให้เจ้าของระบบแก้ไขเอง (Direct-to-Owner)')], default='', max_length=10, verbose_name='เส้นทางที่ Tier 1 เลือก (Admin/Owner)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='key',
            field=models.CharField(choices=[('CONTAINMENT_REQUIRED', 'แจ้งผู้ดูแลระบบ — ต้องดำเนินการควบคุม (Containment required)'), ('CONTAINMENT_SUBMITTED', 'แจ้งเจ้าหน้าที่ SOC — ผู้ดูแลระบบส่งรายงานการควบคุมแล้ว'), ('MANAGER_TRIAGE_PENDING', 'แจ้งผู้จัดการ SOC — มี Incident รอตรวจก่อนมอบหมาย'), ('OWNER_CREATED', 'แจ้งเจ้าของระบบ — เปิด Ticket ใหม่'), ('OWNER_CLOSED', 'แจ้งเจ้าของระบบ — ปิด Ticket แล้ว')], max_length=50, unique=True, verbose_name='ประเภทการแจ้งเตือน'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'แจ้งเหตุใหม่'), ('ESCALATED_T2', 'ส่งต่อให้ Tier 2'), ('T1_REVIEW', 'รอ Tier 1 ทบทวน'), ('PENDING_MGR_TRIAGE', 'รอผู้จัดการ SOC ตรวจ (ก่อนมอบหมาย)'), ('AWAITING_CONTAINMENT', 'รอการจัดการจากผู้ดูแลระบบ'), ('CONTAINMENT_REPORTED', 'รายงานการควบคุมแล้ว'), ('AWAITING_OWNER', 'รอเจ้าของระบบดำเนินการเอง'), ('OWNER_REMEDIATED', 'เจ้าของแจ้งแก้ไขแล้ว — รอ SOC ตรวจ'), ('PENDING_T2_REVIEW', 'รอ Tier 2 ตรวจสอบ'), ('PENDING_MANAGER', 'รอผู้จัดการตรวจสอบ'), ('APPROVED', 'อนุมัติแล้ว'), ('CLOSED_EVENT', 'ปิด (Event)')], default='NEW', max_length=30),
        ),
    ]
