# Generated by Django 6.0.5 on 2026-07-20 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0044_ticket_t1_route_alter_notificationtemplate_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.ticketsubtask', verbose_name='งานย่อยที่เกี่ยวข้อง'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='key',
            field=models.CharField(choices=[('CONTAINMENT_REQUIRED', 'แจ้งผู้ดูแลระบบ — ต้องดำเนินการควบคุม (Containment required)'), ('CONTAINMENT_SUBMITTED', 'แจ้งเจ้าหน้าที่ SOC — ผู้ดูแลระบบส่งรายงานการควบคุมแล้ว'), ('MANAGER_TRIAGE_PENDING', 'แจ้งผู้จัดการ SOC — มี Incident รอตรวจก่อนมอบหมาย'), ('OWNER_CREATED', 'แจ้งเจ้าของระบบ — เปิด Ticket ใหม่'), ('OWNER_CLOSED', 'แจ้งเจ้าของระบบ — ปิด Ticket แล้ว'), ('RESPONSE_REQUEST_CREATED', 'แจ้งทีมตอบสนอง — มีคำขอใหม่ (Forensic / Red Team)'), ('RESPONSE_REQUEST_COMPLETED', 'แจ้งผู้จัดการ SOC — คำขอทีมตอบสนองเสร็จสิ้น')], max_length=50, unique=True, verbose_name='ประเภทการแจ้งเตือน'),
        ),
        migrations.AlterField(
            model_name='ticketsubtask',
            name='subtask_type',
            field=models.CharField(choices=[('INVESTIGATION', 'Investigation'), ('COUNTERMEASURE', 'Countermeasure'), ('VA_PT', 'VA / Pentest'), ('INFRA_SEC', 'Infrastructure Security'), ('FORENSIC_RCA', 'Forensics / RCA')], max_length=20, verbose_name='ประเภท'),
        ),
    ]
