# Generated by Django 6.0.5 on 2026-07-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0045_ticketattachment_subtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='key',
            field=models.CharField(choices=[('CONTAINMENT_REQUIRED', 'แจ้งผู้ดูแลระบบ — ต้องดำเนินการควบคุม (Containment required)'), ('CONTAINMENT_SUBMITTED', 'แจ้งเจ้าหน้าที่ SOC — ผู้ดูแลระบบส่งรายงานการควบคุมแล้ว'), ('MANAGER_TRIAGE_PENDING', 'แจ้งผู้จัดการ SOC — มี Incident รอตรวจก่อนมอบหมาย'), ('OWNER_CREATED', 'แจ้งเจ้าของระบบ — เปิด Ticket ใหม่'), ('OWNER_CLOSED', 'แจ้งเจ้าของระบบ — ปิด Ticket แล้ว'), ('RESPONSE_REQUEST_CREATED', 'แจ้งทีมตอบสนอง — มีคำขอใหม่ (Forensic Analyst / Red Team Manager)'), ('RESPONSE_REQUEST_COMPLETED', 'แจ้งผู้จัดการ SOC — คำขอทีมตอบสนองเสร็จสิ้น')], max_length=50, unique=True, verbose_name='ประเภทการแจ้งเตือน'),
        ),
    ]
