# Generated by Django 6.0.5 on 2026-07-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0046_alter_notificationtemplate_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset_owner_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='ชื่อเจ้าของทรัพย์สิน'),
        ),
    ]
