# Generated by Django 6.0.5 on 2026-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0048_ticket_t2_claimed_at_ticket_t2_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='classification_at_escalation',
            field=models.CharField(blank=True, choices=[('INCIDENT', 'Incident (เหตุการณ์จริง)'), ('EVENT', 'Event (ไม่เป็นภัย)')], default='', max_length=20, verbose_name='ประเภทตอนส่งต่อให้ Tier 2'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'แจ้งเหตุใหม่'), ('ESCALATED_T2', 'ส่งต่อให้ Tier 2'), ('T1_REVIEW', 'รอ Tier 1 ทบทวน'), ('PENDING_MGR_TRIAGE', 'รอผู้จัดการ SOC ตรวจ (ก่อนมอบหมาย)'), ('AWAITING_CONTAINMENT', 'รอการจัดการจากผู้ดูแลระบบ'), ('CONTAINMENT_REPORTED', 'รายงานการควบคุมแล้ว'), ('AWAITING_OWNER', 'รอเจ้าของระบบดำเนินการเอง'), ('OWNER_REMEDIATED', 'เจ้าของแจ้งแก้ไขแล้ว — รอ SOC ตรวจ'), ('PENDING_T2_REVIEW', 'รอ Tier 2 ตรวจสอบ'), ('PENDING_MANAGER', 'รอผู้จัดการตรวจสอบ'), ('PENDING_MGR_EVENT_REVIEW', 'รอผู้จัดการตรวจสอบการปิดแบบ Event'), ('APPROVED', 'อนุมัติแล้ว'), ('CLOSED_EVENT', 'ปิด (Event)')], default='NEW', max_length=30),
        ),
    ]
