# Generated by Django 6.0.5 on 2026-07-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0050_triagerecord_resolved_at_triagerecord_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='deleted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='deleted_attachments',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
