# Generated by Django 6.0.5 on 2026-07-24 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0051_ticketattachment_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='emergency_decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาประเมินสถานะฉุกเฉิน (ครั้งแรก)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='emergency_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_assessed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ประเมินสถานะฉุกเฉิน (ครั้งแรก)'),
        ),
    ]
