# Generated by Django 6.0.5 on 2026-07-24

import apps.incidents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0052_ticket_emergency_decided_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectincident',
            name='actions_taken_summary',
            field=models.TextField(blank=True, default='', verbose_name='สรุปเรื่องที่ดำเนินการแล้ว'),
        ),
        migrations.AddField(
            model_name='projectincident',
            name='emergency_decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาประเมินสถานะฉุกเฉิน'),
        ),
        migrations.AddField(
            model_name='projectincident',
            name='emergency_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_assessed_projects', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ประเมินสถานะฉุกเฉิน'),
        ),
        migrations.AddField(
            model_name='projectincident',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='สถานะฉุกเฉิน'),
        ),
        migrations.AddField(
            model_name='projectincident',
            name='next_steps_summary',
            field=models.TextField(blank=True, default='', verbose_name='สรุปการดำเนินการลำดับถัดไป'),
        ),
        migrations.CreateModel(
            name='ProjectIncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.incidents.models.project_attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.projectincident')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['uploaded_at']},
        ),
        migrations.CreateModel(
            name='ProjectIncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='บันทึกรายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_incident_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='incidents.projectincident')),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
