# Generated by Django 6.0.7 on 2026-08-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0054_stagedattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ioc_user',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='บัญชีผู้ใช้ที่เกี่ยวข้อง (User)'),
        ),
    ]
