# Generated by Django 6.0.7 on 2026-08-06 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0055_ticket_ioc_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedattachment',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='TicketLogRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_note', models.TextField(verbose_name='ข้อความก่อนแก้ไข')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_log_revisions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไข')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='incidents.ticketlog')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
