# Generated by Django 6.0.7 on 2026-08-06 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0056_stagedattachment_discarded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=60)),
                ('field_label', models.CharField(max_length=120)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_field_changes', to=settings.AUTH_USER_MODEL)),
                ('subtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='incidents.ticketsubtask')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='incidents.ticket')),
            ],
            options={
                'ordering': ['-changed_at', 'field_name'],
                'indexes': [models.Index(fields=['ticket', '-changed_at'], name='incidents_t_ticket__d830c9_idx')],
            },
        ),
    ]
