# Generated by Django 6.0.7 on 2026-08-10

from django.db import migrations, models


def backfill_subtask_status_changed_at(apps, schema_editor):
    """Use the best available timestamp for historical rows.

    Earlier versions did not distinguish a status change from another subtask
    edit. ``updated_at`` is therefore the latest known activity, not a claim
    of exact historical status-transition time. New rows are exact.
    """
    TicketSubtask = apps.get_model('incidents', 'TicketSubtask')
    TicketSubtask.objects.filter(status_changed_at__isnull=True).update(
        status_changed_at=models.F('updated_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0057_ticketfieldchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsubtask',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อัปเดตสถานะ'),
        ),
        migrations.RunPython(
            backfill_subtask_status_changed_at,
            migrations.RunPython.noop,
        ),
    ]
