# Generated by Django 6.0.7 on 2026-08-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_primary_alert_links(apps, schema_editor):
    Ticket = apps.get_model('incidents', 'Ticket')
    TicketAlertLink = apps.get_model('incidents', 'TicketAlertLink')
    for ticket in Ticket.objects.exclude(wazuh_alert__isnull=True).iterator():
        TicketAlertLink.objects.get_or_create(
            alert_id=ticket.wazuh_alert_id,
            defaults={
                'ticket_id': ticket.pk,
                'role': 'PRIMARY',
                'linked_by_id': ticket.created_by_id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0058_ticketsubtask_status_changed_at'),
        ('wazuh_ingest', '0006_wazuhalert_project_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAlertLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary alert'), ('SUPPORTING', 'Supporting alert')], max_length=12)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_alert_link', to='wazuh_ingest.wazuhalert')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_alert_links', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_links', to='incidents.ticket')),
            ],
            options={
                'ordering': ['role', 'alert__timestamp', 'alert_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ticketalertlink',
            constraint=models.UniqueConstraint(condition=models.Q(role='PRIMARY'), fields=('ticket',), name='one_primary_alert_per_ticket'),
        ),
        migrations.RunPython(backfill_primary_alert_links, migrations.RunPython.noop),
    ]
