# Generated by Django 6.0.7 on 2026-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0059_ticketalertlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketalertlink',
            options={'ordering': [models.Case(models.When(role='PRIMARY', then=models.Value(0)), default=models.Value(1), output_field=models.IntegerField()), 'alert__timestamp', 'alert_id']},
        ),
    ]
