# Generated by Django 6.0.7 on 2026-08-11 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0060_ticketalertlink_ordering'),
        ('wazuh_ingest', '0006_wazuhalert_project_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'severity'], name='ix_ticket_status_severity'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='ix_ticket_created_at'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['closed_at'], name='ix_ticket_closed_at'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(condition=models.Q(('status__in', ['APPROVED', 'CLOSED_EVENT']), _negated=True), fields=['ola_contain_deadline'], name='ix_ticket_open_contain_ola'),
        ),
    ]
