# Generated by Django 6.0.7 on 2026-08-13 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0061_ticket_ix_ticket_status_severity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectincidentattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectincidentattachment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_project_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectincidentattachment',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
