# Generated by Django 6.0.7 on 2026-08-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0062_project_attachment_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='system_detail',
            field=models.TextField(blank=True, default='', verbose_name='รายละเอียดเฉพาะระบบ'),
        ),
    ]
