# Generated by Django 6.0.7 on 2026-08-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0063_ticket_system_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='mitre_phase',
            new_name='mitre_tactics',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mitre_tactics',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='MITRE ATT&CK Tactics (ยุทธวิธีการโจมตี)'),
        ),
    ]
