# Generated by Django 6.0.7 on 2026-09-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0064_rename_mitre_phase_to_tactics'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='has_been_monitored',
            field=models.BooleanField(default=False, verbose_name='เคยถูกเฝ้าระวังแล้ว'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='monitor_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เฝ้าระวังจนถึง'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='monitoring_proposed',
            field=models.BooleanField(default=False, verbose_name='Tier 1 แนะนำให้เฝ้าระวัง'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'แจ้งเหตุใหม่'), ('ESCALATED_T2', 'ส่งต่อให้ Tier 2'), ('MONITORING', 'กำลังเฝ้าระวัง (Monitoring)'), ('T1_REVIEW', 'รอ Tier 1 ทบทวน'), ('PENDING_MGR_TRIAGE', 'รอผู้จัดการ SOC ตรวจ (ก่อนมอบหมาย)'), ('AWAITING_CONTAINMENT', 'รอการจัดการจากผู้ดูแลระบบ'), ('CONTAINMENT_REPORTED', 'รายงานการควบคุมแล้ว'), ('AWAITING_OWNER', 'รอเจ้าของระบบดำเนินการเอง'), ('OWNER_REMEDIATED', 'เจ้าของแจ้งแก้ไขแล้ว — รอ SOC ตรวจ'), ('PENDING_T2_REVIEW', 'รอ Tier 2 ตรวจสอบ'), ('PENDING_MANAGER', 'รอผู้จัดการตรวจสอบ'), ('PENDING_MGR_EVENT_REVIEW', 'รอผู้จัดการตรวจสอบการปิดแบบ Event'), ('APPROVED', 'อนุมัติแล้ว'), ('CLOSED_EVENT', 'ปิด (Event)')], default='NEW', max_length=30),
        ),
    ]
