# Generated by Django 6.0.7 on 2026-09-08 04:36

import apps.incidents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0065_ticket_monitoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('file_name', 'File Name'), ('hash', 'Hash (SHA-256)'), ('domain', 'Domain'), ('ip', 'IP Address'), ('url', 'URL'), ('file_path', 'File Path')], db_index=True, max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='incidents.ticket')),
            ],
            options={
                'ordering': ['category', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TIPlatformImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.incidents.models.ti_import_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('added_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TIPlatformIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('hash', 'Hash'), ('ip', 'IP'), ('domain', 'Domain'), ('url', 'URL'), ('file_path', 'File Path')], db_index=True, max_length=20)),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ioc_detail', models.CharField(db_index=True, max_length=500)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seen_iocs', to='incidents.tiplatformimport')),
                ('source_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_iocs', to='incidents.tiplatformimport')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TIPlatformIOCStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('reason', models.CharField(max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='incidents.tiplatformioc')),
            ],
            options={
                'ordering': ['-changed_at', '-pk'],
            },
        ),
    ]
