# Generated by Django 6.0.7 on 2026-09-08 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0067_backfill_ticket_iocs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tiplatformioc',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiplatformioc',
            name='last_seen_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seen_iocs', to='incidents.tiplatformimport'),
        ),
        migrations.AlterField(
            model_name='tiplatformioc',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='added_iocs', to='incidents.tiplatformimport'),
        ),
    ]
