# Generated by Django 6.0.7 on 2026-09-08 09:05

import apps.incidents.ip_addresses
from django.db import migrations, models


def remove_inet_host_masks(apps, schema_editor):
    # PostgreSQL's inet::text adds /32 or /128 even for a single host.
    # The old field could only store one address, so remove that cast artifact.
    if schema_editor.connection.vendor == 'postgresql':
        ticket = apps.get_model('incidents', 'Ticket')
        table = schema_editor.quote_name(ticket._meta.db_table)
        schema_editor.execute(
            f"UPDATE {table} SET ip_address = split_part(ip_address, '/', 1) "
            "WHERE ip_address LIKE '%%/%%'"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0068_tiplatformioc_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ip_address',
            field=models.TextField(help_text='ระบุ IPv4 หรือ IPv6 ได้หลายรายการ คั่นด้วยจุลภาคหรือขึ้นบรรทัดใหม่', null=True, validators=[apps.incidents.ip_addresses.validate_ip_addresses], verbose_name='IP Addresses ของทรัพย์สิน'),
        ),
        migrations.RunPython(remove_inet_host_masks, migrations.RunPython.noop),
    ]
