# Generated by Django 6.0.7 on 2026-09-08 09:20

import apps.incidents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0069_ticket_multiple_ip_addresses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiplatformioc',
            name='source_import',
        ),
        migrations.RemoveField(
            model_name='tiplatformioc',
            name='last_seen_import',
        ),
        migrations.RemoveField(
            model_name='tiplatformioc',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='tiplatformiocstatuschange',
            name='ioc',
        ),
        migrations.RemoveField(
            model_name='tiplatformiocstatuschange',
            name='changed_by',
        ),
        migrations.CreateModel(
            name='AnalystIOCImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.incidents.models.ti_import_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('added_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AnalystIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('hash', 'Hash'), ('ip', 'IP'), ('domain', 'Domain'), ('url', 'URL'), ('file_path', 'File Path')], db_index=True, max_length=20)),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ioc_detail', models.CharField(db_index=True, max_length=500)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_seen_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seen_iocs', to='incidents.analystiocimport')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='added_iocs', to='incidents.analystiocimport')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='IOCReviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('file_name', 'File Name'), ('hash', 'Hash (SHA-256)'), ('domain', 'Domain'), ('ip', 'IP Address'), ('url', 'URL'), ('file_path', 'File Path')], db_index=True, max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('checked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.DeleteModel(
            name='TIPlatformImport',
        ),
        migrations.DeleteModel(
            name='TIPlatformIOC',
        ),
        migrations.DeleteModel(
            name='TIPlatformIOCStatusChange',
        ),
    ]
