# Generated by Django 6.0.7 on 2026-09-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0070_remove_tiplatformioc_source_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystiocimport',
            name='restored_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
