# Generated by Django 6.0.7 on 2026-09-10 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0072_remove_analystioc_last_seen_import_and_more'),
        ('wazuh_ingest', '0007_wazuhalert_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DUPLICATE', 'รายการซ้ำ'), ('CREATED_IN_ERROR', 'สร้างรายการผิด'), ('OTHER', 'เหตุผลอื่น')], max_length=24, verbose_name='ประเภทเหตุผล')),
                ('explanation', models.TextField(verbose_name='รายละเอียดเหตุผล')),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติยกเลิกแล้ว'), ('REJECTED', 'ไม่อนุมัติ'), ('WITHDRAWN', 'ถอนคำขอแล้ว'), ('SUPERSEDED', 'สิ้นสุดคำขอเนื่องจากรายการปิดแล้ว')], default='PENDING', max_length=16, verbose_name='สถานะคำขอ')),
                ('mode', models.CharField(choices=[('REVIEW', 'ผู้จัดการพิจารณาคำขอ'), ('CREATOR', 'ผู้เปิดยกเลิกรายการใหม่'), ('MANAGER', 'ผู้จัดการยกเลิกโดยตรง')], default='REVIEW', max_length=12, verbose_name='วิธีอนุมัติ')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ขอ')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ตัดสินใจ')),
                ('decision_note', models.TextField(blank=True, verbose_name='บันทึกการตัดสินใจ')),
                ('cancelled_subtask_ids', models.JSONField(blank=True, default=list, verbose_name='งานย่อยที่ยกเลิก')),
            ],
            options={
                'ordering': ['-requested_at', '-pk'],
                'verbose_name': 'คำขอยกเลิกรายการ',
                'verbose_name_plural': 'คำขอยกเลิกรายการ',
            },
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='ix_ticket_open_contain_ola',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'แจ้งเหตุใหม่'), ('ESCALATED_T2', 'ส่งต่อให้ Tier 2'), ('MONITORING', 'กำลังเฝ้าระวัง (Monitoring)'), ('T1_REVIEW', 'รอ Tier 1 ทบทวน'), ('PENDING_MGR_TRIAGE', 'รอผู้จัดการ SOC ตรวจ (ก่อนมอบหมาย)'), ('AWAITING_CONTAINMENT', 'รอการจัดการจากผู้ดูแลระบบ'), ('CONTAINMENT_REPORTED', 'รายงานการควบคุมแล้ว'), ('AWAITING_OWNER', 'รอเจ้าของระบบดำเนินการเอง'), ('OWNER_REMEDIATED', 'เจ้าของแจ้งแก้ไขแล้ว — รอ SOC ตรวจ'), ('PENDING_T2_REVIEW', 'รอ Tier 2 ตรวจสอบ'), ('PENDING_MANAGER', 'รอผู้จัดการตรวจสอบ'), ('PENDING_MGR_EVENT_REVIEW', 'รอผู้จัดการตรวจสอบการปิดแบบ Event'), ('APPROVED', 'อนุมัติแล้ว'), ('CLOSED_EVENT', 'ปิด (Event)'), ('CANCELLED', 'ยกเลิกแล้ว')], default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketsubtask',
            name='status',
            field=models.CharField(choices=[('OPEN', 'เปิด'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('DONE', 'เสร็จสิ้น'), ('CANCELLED', 'ยกเลิกแล้ว')], default='OPEN', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(condition=models.Q(('status__in', ['APPROVED', 'CLOSED_EVENT', 'CANCELLED']), _negated=True), fields=['ola_contain_deadline'], name='ix_ticket_open_contain_ola'),
        ),
        migrations.AddField(
            model_name='ticketcancellationrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตัดสินใจ'),
        ),
        migrations.AddField(
            model_name='ticketcancellationrequest',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='incidents.ticket', verbose_name='รายการต้นฉบับ'),
        ),
        migrations.AddField(
            model_name='ticketcancellationrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอ'),
        ),
        migrations.AddField(
            model_name='ticketcancellationrequest',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests', to='incidents.ticket', verbose_name='รายการ'),
        ),
        migrations.AddConstraint(
            model_name='ticketcancellationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('ticket',), name='one_pending_ticket_cancellation'),
        ),
        migrations.AddConstraint(
            model_name='ticketcancellationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('ticket', models.F('duplicate_of')), _negated=True), name='cancellation_duplicate_not_self'),
        ),
    ]
