# Generated by Django 6.0.7 on 2026-09-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0073_ticket_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันและเวลาที่เกิดเหตุการณ์'),
        ),
    ]
