# Generated by Django 6.0.7 on 2026-09-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0074_event_occurred_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ioc_command',
            field=models.TextField(blank=True, default='', help_text='คำสั่งที่ผู้โจมตีสั่งรัน — หนึ่งบรรทัดต่อหนึ่งคำสั่ง', verbose_name='คำสั่ง (Command)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remediation_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remediation_other',
            field=models.TextField(blank=True, default='', verbose_name='สรุปผลการดำเนินการแก้ไข — อื่นๆ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ioc_user',
            field=models.CharField(blank=True, default='', help_text='บัญชีผู้ใช้ที่ผู้โจมตีใช้ในการโจมตี เช่น administrator หรือ DOMAIN\\svc_backup', max_length=150, verbose_name='บัญชีผู้ใช้ที่เกี่ยวข้อง (User)'),
        ),
    ]
