# Generated by Django 6.0.7 on 2026-09-14 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0075_report_batch3_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analystioc',
            name='source_subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pushed_iocs', to='incidents.ticketsubtask'),
        ),
        migrations.CreateModel(
            name='RCAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ชื่อเหตุการณ์')),
                ('first_occurrence', models.TextField(blank=True, default='', verbose_name='วันที่/เวลา ที่เกิดเหตุครั้งแรก (ยืนยันได้)')),
                ('detected_text', models.TextField(blank=True, default='', verbose_name='วันที่/เวลา ที่ตรวจพบ')),
                ('scope_period', models.TextField(blank=True, default='', verbose_name='ช่วงเวลาที่ตรวจพิสูจน์ (Scope)')),
                ('forensic_types', models.JSONField(blank=True, default=list, verbose_name='ประเภทการตรวจพิสูจน์')),
                ('importance', models.CharField(blank=True, choices=[('general', 'ปกติทั่วไป'), ('important', 'สำคัญ'), ('critical', 'สำคัญมาก')], default='', max_length=20, verbose_name='ระดับความสำคัญ')),
                ('siem_severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20, verbose_name='ระดับความรุนแรง (อ้างอิงตามระบบ SIEM)')),
                ('ncsa_severity', models.CharField(blank=True, choices=[('CRITICAL', 'วิกฤต (Critical)'), ('SEVERE', 'ร้ายแรง (Severe)'), ('NON_SEVERE', 'ไม่ร้ายแรง (Non-Severe)')], default='', max_length=20, verbose_name='ระดับความรุนแรง (อ้างอิงตาม สกมช.)')),
                ('threat_category', models.CharField(blank=True, choices=[('Training', 'เหตุการณ์จำลอง และ การฝึกจู่โจม ของหน่วยงานเอง (Training and Exercises)'), ('Unsuccessful Attempt', 'การพยายามเข้าถึงระบบที่ไม่สำเร็จ (Unsuccessful Activity Attempt)'), ('Reconnaissance', 'การพยายามบุกรุกเพื่อสำรวจข้อมูลองค์กรเพื่อโจมตี (Reconnaissance)'), ('Non-Compliance', 'การดำเนินการที่ไม่เป็นไปตามมาตรฐานความปลอดภัยที่หน่วยงานกำหนด (Non-Compliance Activity)'), ('Malicious Logic', 'การบุกรุกโดยการใช้มัลแวร์ (Malicious Logic)'), ('User Intrusion', 'การบุกรุกในระดับผู้ใช้งาน (User Level Intrusion)'), ('Root Intrusion', 'การบุกรุกในระดับผู้ควบคุมระบบ (Root Level Intrusion)'), ('DoS', 'การบุกรุกที่ทำให้ไม่สามารถเข้าไปใช้บริการได้ (Denial of Service)'), ('Investigating', 'เหตุการณ์ที่อยู่ระหว่างการวิเคราะห์สอบสวน (Investigating)'), ('Explained Anomaly', 'เหตุการณ์ผิดปกติที่ได้รับการวิเคราะห์แล้วว่าไม่ใช่เหตุการณ์ที่เป็นภัยคุกคาม (Explained Anomaly)'), ('SIEM Other', 'อื่นๆ (SIEM Other)'), ('Admin Unsuccessful', '(Admin) การพยายามเข้าถึงระบบที่ไม่สำเร็จ (Unsuccessful Activity Attempt)'), ('Admin Reconnaissance', '(Admin) การพยายามบุกรุกเพื่อสำรวจข้อมูลองค์กรเพื่อโจมตี (Reconnaissance)'), ('Admin Non-Compliance', '(Admin) การดำเนินการที่ไม่เป็นไปตามมาตรฐานความปลอดภัยที่หน่วยงานกำหนด (Non-Compliance Activity)'), ('Admin Malicious Logic', '(Admin) การบุกรุกโดยการใช้มัลแวร์ (Malicious Logic)'), ('Admin User Intrusion', '(Admin) การบุกรุกในระดับผู้ใช้งาน (User Level Intrusion)'), ('Admin Root Intrusion', '(Admin) การบุกรุกในระดับผู้ควบคุมระบบ (Root Level Intrusion)'), ('Admin DoS', '(Admin) การบุกรุกที่ทำให้ไม่สามารถเข้าไปใช้บริการได้ (Denial of Service)'), ('Admin Explained Anomaly', '(Admin) เหตุการณ์ผิดปกติที่ได้รับการวิเคราะห์แล้วว่าไม่ใช่เหตุการณ์ที่เป็นภัยคุกคาม (Explained Anomaly)'), ('TI IOC', 'แจ้งเตือน IOC (Indicators of Compromise)'), ('TI Other', 'อื่นๆ (TI Other)'), ('Data Leak', 'พบข้อมูลรั่วไหล'), ('Vulnerability', 'พบช่องโหว่ของอุปกรณ์หรือระบบงาน'), ('Attack Attempt', 'พบความพยายามในการไปโจมตีผู้อื่น'), ('External Other', 'อื่นๆ (External Other)')], default='', max_length=50, verbose_name='หมวดหมู่ของภัยคุกคามทางไซเบอร์')),
                ('assets_examined', models.TextField(blank=True, default='', verbose_name='ทรัพย์สินที่นำเข้าตรวจพิสูจน์')),
                ('asset_type', models.CharField(blank=True, choices=[('Computer', 'Computer'), ('Server', 'Server'), ('Network Device', 'Network Device')], default='', max_length=50, verbose_name='ประเภททรัพย์สิน')),
                ('affected_systems', models.TextField(blank=True, default='', verbose_name='ระบบ/บริการที่ได้รับผลกระทบ')),
                ('asset_owner', models.TextField(blank=True, default='', verbose_name='ส่วนงานเจ้าของหรือผู้ดูแลทรัพย์สิน')),
                ('examiner', models.CharField(blank=True, default='', max_length=255, verbose_name='ผู้ตรวจพิสูจน์')),
                ('related_refs', models.TextField(blank=True, default='', verbose_name='เลขอ้างอิงที่เกี่ยวข้อง')),
                ('draft_generated_at', models.DateTimeField(blank=True, null=True)),
                ('draft_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('draft_template_version', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rca', to='incidents.ticketsubtask', verbose_name='คำขอ Forensics / RCA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RCAAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('host', models.CharField(max_length=255, verbose_name='เครื่อง')),
                ('ip', models.CharField(blank=True, default='', max_length=255, verbose_name='IP Address')),
                ('detail', models.TextField(blank=True, default='', verbose_name='ระบบปฏิบัติการ / รายละเอียด')),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='incidents.rcareport')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RCARootCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='ประเภท')),
                ('cause', models.TextField(verbose_name='สาเหตุ')),
                ('evidence_ref', models.TextField(blank=True, default='', verbose_name='ไฟล์หลักฐาน / Event ID / บรรทัด')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='ตัวอย่างจากไฟล์หลักฐาน')),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='incidents.rcareport')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RCARecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('action', models.TextField(verbose_name='สิ่งที่ควรดำเนินการ')),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='incidents.rcareport')),
                ('root_causes', models.ManyToManyField(blank=True, related_name='recommendations', to='incidents.rcarootcause', verbose_name='แก้ที่ Root Cause')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RCATimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(verbose_name='วัน/เวลา')),
                ('occurred_until', models.DateTimeField(blank=True, null=True, verbose_name='ถึงเวลา')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='เครื่อง')),
                ('event', models.TextField(verbose_name='เหตุการณ์')),
                ('evidence_file', models.CharField(blank=True, default='', max_length=255, verbose_name='ไฟล์หลักฐาน')),
                ('evidence_line', models.CharField(blank=True, default='', max_length=64, verbose_name='บรรทัด')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='ตัวอย่างจากไฟล์หลักฐาน')),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incidents.rcareport')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RCAIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('file_path', 'File Path'), ('ip', 'IP Address'), ('url', 'URL'), ('domain', 'Domain'), ('email', 'Email'), ('hash', 'Hash (SHA-256)'), ('account', 'บัญชีผู้ใช้')], max_length=20, verbose_name='ประเภท IOC')),
                ('value', models.CharField(max_length=500, verbose_name='Indicator')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='เครื่อง')),
                ('label', models.TextField(blank=True, default='', verbose_name='ประเภท / ไฟล์ที่พบ')),
                ('note', models.TextField(blank=True, default='', verbose_name='หมายเหตุ / บทบาทในเหตุการณ์')),
                ('excluded', models.BooleanField(default=False, verbose_name='Exclude (ไม่ส่งเข้า IOC Database)')),
                ('source', models.CharField(choices=[('ticket', 'จาก Ticket'), ('analyst', 'Forensic พบเพิ่ม')], default='analyst', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pushed_ioc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incidents.analystioc')),
                ('rca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='incidents.rcareport')),
            ],
            options={
                'ordering': ['category', 'order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('rca', 'category', 'value'), name='rca_indicator_unique_value')],
            },
        ),
    ]
