# Generated by Django 6.0.7 on 2026-09-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0076_rca_report'),
    ]

    operations = [
        # first_occurrence changes TextField -> DateTimeField. A plain AlterField
        # would emit a USING ::timestamp cast that fails on any existing Thai
        # date-string row, so drop and re-add it (values are re-pullable from the
        # ticket). detected_text/scope_period likewise go for text->datetime.
        migrations.RemoveField(
            model_name='rcareport',
            name='first_occurrence',
        ),
        migrations.RemoveField(
            model_name='rcareport',
            name='detected_text',
        ),
        migrations.RemoveField(
            model_name='rcareport',
            name='scope_period',
        ),
        migrations.AddField(
            model_name='rcareport',
            name='first_occurrence',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่/เวลา ที่เกิดเหตุครั้งแรก'),
        ),
        migrations.AddField(
            model_name='rcareport',
            name='detected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่/เวลา ที่ตรวจพบ'),
        ),
        migrations.AddField(
            model_name='rcareport',
            name='first_occurrence_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='หมายเหตุเวลาที่เกิดเหตุ (เช่น โดยประมาณ/ยืนยันไม่ได้)'),
        ),
        migrations.AddField(
            model_name='rcareport',
            name='scope_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ช่วงเวลาที่ตรวจพิสูจน์ — ถึง'),
        ),
        migrations.AddField(
            model_name='rcareport',
            name='scope_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ช่วงเวลาที่ตรวจพิสูจน์ — เริ่ม'),
        ),
    ]
