# Generated by Django 6.0.7 on 2026-09-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0077_remove_rcareport_detected_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'กำลังจัดเตรียม (ยังไม่ส่ง)'), ('ESCALATED_T2', 'ส่งต่อให้ Tier 2'), ('MONITORING', 'กำลังเฝ้าระวัง (Monitoring)'), ('T1_REVIEW', 'รอ Tier 1 ทบทวน'), ('PENDING_MGR_TRIAGE', 'รอผู้จัดการ SOC ตรวจ (ก่อนมอบหมาย)'), ('AWAITING_CONTAINMENT', 'รอการจัดการจากผู้ดูแลระบบ'), ('CONTAINMENT_REPORTED', 'รายงานการควบคุมแล้ว'), ('AWAITING_OWNER', 'รอเจ้าของระบบดำเนินการเอง'), ('OWNER_REMEDIATED', 'เจ้าของแจ้งแก้ไขแล้ว — รอ SOC ตรวจ'), ('PENDING_T2_REVIEW', 'รอ Tier 2 ตรวจสอบ'), ('PENDING_MANAGER', 'รอผู้จัดการตรวจสอบ'), ('PENDING_MGR_EVENT_REVIEW', 'รอผู้จัดการตรวจสอบการปิดแบบ Event'), ('APPROVED', 'อนุมัติแล้ว'), ('CLOSED_EVENT', 'ปิด (Event)'), ('CANCELLED', 'ยกเลิกแล้ว')], default='NEW', max_length=30),
        ),
    ]
