# Generated by Django 6.0.7 on 2026-09-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0078_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='affected_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ เวลา ที่แจ้งเหตุผู้ที่ได้รับผลกระทบ'),
        ),
    ]
