# Generated by Django 6.0.7 on 2026-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0079_ticket_affected_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcareport',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('Computer', 'คอมพิวเตอร์'), ('Server', 'เซิร์ฟเวอร์'), ('Network Device', 'Network Device')], default='', max_length=50, verbose_name='ประเภททรัพย์สิน'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('Computer', 'คอมพิวเตอร์'), ('Server', 'เซิร์ฟเวอร์'), ('Network Device', 'Network Device')], default='', max_length=20, verbose_name='ประเภทของทรัพย์สิน'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('SIEM', 'ระบบเฝ้าระวัง (SIEM)'), ('ADMIN', 'ผู้ดูแลระบบ (Admin)'), ('TI', 'ข้อมูลข่าวกรองภัยคุกคาม (TI)'), ('EMAIL', 'อีเมล'), ('PHONE', 'โทรศัพท์ / สายด่วน'), ('USER_REPORT', 'ผู้ใช้ / รายงานภายใน'), ('EXTERNAL', 'หน่วยงานภายนอก (External Organization)'), ('OTHER', 'Other')], default='SIEM', max_length=50, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='ticketalertlink',
            name='role',
            field=models.CharField(choices=[('PRIMARY', 'การแจ้งเตือนหลัก'), ('SUPPORTING', 'การแจ้งเตือนประกอบ')], max_length=12),
        ),
        migrations.AlterField(
            model_name='ticketsubtask',
            name='subtask_type',
            field=models.CharField(choices=[('INVESTIGATION', 'การสืบสวน'), ('COUNTERMEASURE', 'มาตรการตอบโต้'), ('VA_PT', 'ประเมินช่องโหว่ / ทดสอบเจาะระบบ (VA/PT)'), ('INFRA_SEC', 'ความปลอดภัยโครงสร้างพื้นฐาน (Hardening)'), ('FORENSIC_RCA', 'Forensics / RCA')], max_length=20, verbose_name='ประเภท'),
        ),
        migrations.AlterField(
            model_name='triagerecord',
            name='source',
            field=models.CharField(choices=[('SIEM', 'ระบบเฝ้าระวัง (SIEM)'), ('ADMIN', 'ผู้ดูแลระบบ (Admin)'), ('TI', 'ข้อมูลข่าวกรองภัยคุกคาม (TI)'), ('EMAIL', 'อีเมล'), ('PHONE', 'โทรศัพท์ / สายด่วน'), ('USER_REPORT', 'ผู้ใช้ / รายงานภายใน'), ('EXTERNAL', 'หน่วยงานภายนอก (External Organization)'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='แหล่งที่มาของ Alert'),
        ),
    ]
