# Generated by Django 6.0.7 on 2026-09-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0080_alter_rcareport_asset_type_alter_ticket_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_summary',
            field=models.TextField(blank=True, default='', verbose_name='สรุปเหตุการณ์'),
        ),
    ]
