# Generated by Django 6.0.7 on 2026-09-22 07:40

from django.db import migrations, models
from django.db.models import F, OuterRef, Subquery
from django.db.models.functions import Coalesce
from django.utils import timezone

# T1_REVIEW is retired: Tier 2 now picks the handling lane and routes a
# confirmed Incident straight to the SOC Manager, and the manager's "return for
# completion" goes back to whoever routed it (Tier 2, or Tier 1's preparation).
# Tickets still sitting in T1_REVIEW are handed back to Tier 2 to make that
# decision. Old TicketLog rows keep status_at_time='T1_REVIEW' — the audit trail
# is not rewritten; Ticket.LEGACY_STATUS_LABELS renders it.

MOVE_NOTE = (
    'ระบบย้าย Ticket จากสถานะ "รอ Tier 1 ทบทวน" (ยกเลิกขั้นตอนนี้แล้ว) '
    'กลับไปยัง Tier 2 — Tier 2 เลือกเส้นทางการจัดการและส่งผู้จัดการ SOC'
)


def forwards(apps, schema_editor):
    Ticket = apps.get_model('incidents', 'Ticket')
    TicketLog = apps.get_model('incidents', 'TicketLog')

    # first_submitted_at: when each already-submitted ticket first left NEW —
    # its earliest non-NEW log row, falling back to the last status change.
    first_out = (
        TicketLog.objects.filter(ticket=OuterRef('pk'))
        .exclude(status_at_time='NEW')
        .order_by('created_at')
        .values('created_at')[:1]
    )
    Ticket.objects.exclude(status='NEW').filter(first_submitted_at__isnull=True).update(
        first_submitted_at=Coalesce(Subquery(first_out), F('status_changed_at'), F('created_at')),
    )

    now = timezone.now()
    for ticket in Ticket.objects.filter(status='T1_REVIEW'):
        ticket.status = 'ESCALATED_T2'
        ticket.classification_at_escalation = ticket.classification or 'INCIDENT'
        ticket.t2_claimed_by = None
        ticket.t2_claimed_at = None
        ticket.status_changed_at = now
        if ticket.escalated_to_t2_at is None:
            ticket.escalated_to_t2_at = now
        ticket.save(update_fields=[
            'status', 'classification_at_escalation', 't2_claimed_by',
            't2_claimed_at', 'status_changed_at', 'escalated_to_t2_at',
        ])
        TicketLog.objects.create(
            ticket=ticket, note=MOVE_NOTE, status_at_time='ESCALATED_T2', author=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0082_remove_ticket_monitoring_proposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creator_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ผู้เปิด Ticket เปิดดูล่าสุด'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ส่ง Ticket ครั้งแรก'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='t2_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tier 2 แก้ไขข้อมูลล่าสุด'),
        ),
        # One-way: T1_REVIEW no longer exists to move tickets back into.
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'กำลังจัดเตรียม (ยังไม่ส่ง)'), ('ESCALATED_T2', 'ส่งต่อให้ Tier 2'), ('MONITORING', 'กำลังเฝ้าระวัง (Monitoring)'), ('PENDING_MGR_TRIAGE', 'รอผู้จัดการ SOC ตรวจ (ก่อนมอบหมาย)'), ('AWAITING_CONTAINMENT', 'รอการจัดการจากผู้ดูแลระบบ'), ('CONTAINMENT_REPORTED', 'รายงานการควบคุมแล้ว'), ('AWAITING_OWNER', 'รอเจ้าของระบบดำเนินการเอง'), ('OWNER_REMEDIATED', 'เจ้าของแจ้งแก้ไขแล้ว — รอ SOC ตรวจ'), ('PENDING_T2_REVIEW', 'รอ Tier 2 ตรวจสอบ'), ('PENDING_MANAGER', 'รอผู้จัดการตรวจสอบ'), ('PENDING_MGR_EVENT_REVIEW', 'รอผู้จัดการตรวจสอบการปิดแบบ Event'), ('APPROVED', 'อนุมัติแล้ว'), ('CLOSED_EVENT', 'ปิด (Event)'), ('CANCELLED', 'ยกเลิกแล้ว')], default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t1_route',
            field=models.CharField(blank=True, choices=[('ADMIN', 'มอบหมายผู้ดูแลระบบ (System Admin)'), ('OWNER', 'ให้เจ้าของระบบแก้ไขเอง (Direct-to-Owner)')], default='', max_length=10, verbose_name='เส้นทางการจัดการ (Admin/Owner)'),
        ),
    ]
