# Generated by Django 6.0.7 on 2026-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0083_purge_t1_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='importance',
            field=models.CharField(blank=True, choices=[('general', 'ปกติทั่วไป'), ('important', 'สำคัญ'), ('critical', 'สำคัญมาก')], default='', max_length=20, verbose_name='ระดับความสำคัญ'),
        ),
    ]
