# Generated by Django 6.0.7 on 2026-09-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0085_alter_ticket_detailed_issue2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='incident_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ชื่อเรื่อง (Incident/Event Name)'),
        ),
    ]
