# Generated by Django 6.0.7 on 2026-09-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0086_alter_ticket_incident_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsubtask',
            name='report_number',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='เลขที่รายงาน'),
        ),
    ]
