# Generated by Django 6.0.7 on 2026-09-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0088_alter_ticket_ip_address_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsubtask',
            name='subtask_type',
            field=models.CharField(choices=[('INVESTIGATION', 'การสืบสวน'), ('COUNTERMEASURE', 'มาตรการตอบโต้'), ('VA', 'ประเมินช่องโหว่ (VA)'), ('PENTEST', 'ทดสอบเจาะระบบ (PenTest)'), ('HARDENING', 'ปรับความมั่นคงปลอดภัย (Hardening)'), ('FORENSIC_RCA', 'Forensics / RCA'), ('VA_PT', 'VA/PT (เดิม)'), ('INFRA_SEC', 'Hardening (เดิม)')], max_length=20, verbose_name='ประเภท'),
        ),
    ]
